APPNAME:=AndroidTriangle
ANDROIDSRCS:= src/App.c
ROOT_DIR:=$(abspath ../../)

all: apk

test:
	@echo $(LIB_DIR)

clean:
	rm -rf build
	rm -f my-release-key.keystore

include ../../makefiles/AndroidAPK.mk