name: Build Executable

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #[windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install make build-essential libx11-dev libxcursor-dev libxrandr-dev
 
    - name: Build
      run: |
        make && make clean_objs

    - uses: actions/upload-artifact@v2
      with:
        name: MuttonLib
        path: build