name: Build Executable

on: [push]

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MinGW",
            os: windows-latest,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja"
          }
        - {
            name: "Ubuntu_Latest_GCC",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja"
          }
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja"
          }

    steps:
    - uses: actions/checkout@v1
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e

    - name: Install dependencies on windows
      if: startsWith(matrix.config.os, 'windows')
      run: |
        choco install ninja cmake
        ninja --version
        cmake --version

    - name: Install dependencies on ubuntu
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build cmake xorg-dev
        ninja --version
        cmake --version
        gcc --version

    - name: Install dependencies on macos
      if: startsWith(matrix.config.os, 'macos')
      run: |
        brew install cmake ninja
        ninja --version
        cmake --version
 
    - name: Build Desktop
      run: |
        cmake -S . -B desktopbuild -DBUILD_DESKTOP=ON -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -G "${{ matrix.config.generators }}"
        cmake --build desktopbuild --config ${{ matrix.config.build_type }}

    - name: Build Android
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        cmake -S . -B androidbuild -DBUILD_ANDROID=ON -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -G "${{ matrix.config.generators }}"
        cmake --build androidbuild --config ${{ matrix.config.build_type }}

    - uses: actions/upload-artifact@v2
      with:
        name: MuttonLib
        path: build